name: Terraform Manual Deploy

on:
  workflow_dispatch:
    inputs:
      tfvars_file:
        description: "Nombre del archivo .tfvars (debe estar en infra/)"
        required: true
        default: "terraform.tfvars"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login en Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.6"

      - name: Inicializar Terraform
        working-directory: infra
        run: terraform init

      - name: Validar configuración
        working-directory: infra
        run: terraform validate

      - name: Plan de Terraform
        working-directory: infra
        run: terraform plan -var-file=${{ github.event.inputs.tfvars_file }}

      - name: Aplicar cambios
        working-directory: infra
        run: terraform apply -auto-approve -var-file=${{ github.event.inputs.tfvars_file }}
